/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_za_pc_remote_desktop_agent_EventSender */

#ifndef _Included_hu_za_pc_remote_desktop_agent_EventSender
#define _Included_hu_za_pc_remote_desktop_agent_EventSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_za_pc_remote_desktop_agent_EventSender
 * Method:    sendMouseMove
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hu_za_pc_1remote_desktop_1agent_EventSender_sendMouseMove
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hu_za_pc_remote_desktop_agent_EventSender
 * Method:    sendMouseClick
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hu_za_pc_1remote_desktop_1agent_EventSender_sendMouseClick
  (JNIEnv *, jobject, jint);

/*
 * Class:     hu_za_pc_remote_desktop_agent_EventSender
 * Method:    sendKeyPress
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_hu_za_pc_1remote_desktop_1agent_EventSender_sendKeyPress
  (JNIEnv *, jobject, jchar);

#ifdef __cplusplus
}
#endif
#endif
